project:
  type: website

website:
  title: "Arno's Data Science Snippets"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/arnos-stuff
      - icon: twitter
        href: https://twitter.com/arno_shae
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: tomorrow-night-blue



